version: '2'
services:
    jhipster-registry:
        extends:
            file: registry.yml
            service: jhipster-registry
        volumes:
            - ./central-server-config:/central-config
        environment:
            - GIT_URI=https://github.com/jhipster/jhipster-registry/
            - GIT_SEARCH_PATH=central-config

    gateway:
        extends:
            file: /home/ippon/docker-compose-subgen-demo/gateway/src/main/docker/app.prod.yml
            service: gateway-app
    gateway-mysql:
        extends:
            file: /home/ippon/docker-compose-subgen-demo/gateway/src/main/docker/db.prod.yml
            service: gateway-mysql

    msapp:
        extends:
            file: /home/ippon/docker-compose-subgen-demo/msapp/src/main/docker/app.prod.yml
            service: msapp-app
    msapp-mysql:
        extends:
            file: /home/ippon/docker-compose-subgen-demo/msapp/src/main/docker/db.prod.yml
            service: msapp-mysql

    elk-elasticsearch:
        extends:
            file: elk.yml
            service: elk-elasticsearch
    elk-logstash:
        extends:
          file: elk.yml
          service: elk-logstash
    jhipster-console:
        extends:
            file: elk.yml
            service: jhipster-console
